### ISSUE TITLE
Replace CircleCI with Github actions

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-label-sync#1]
It would be nice to approve merging directly from within the Github UI by using the new actions feature.

**Comment by maticzav** [comment]
#11 

We can still work on this though

**Comment by schickling** [comment]
Why did you close this @janpio?

**Comment by janpio** [comment]
Because it is nothing that can be implemented in `prisma-label-sync`, but `label-sync` if at all: As explained in #11 Github Actions work on a different scope that would require changing the full architecture of `label-sync` (Actions are installed on the individual repos that should use them, vs. this central repository that contains the config for all repos and applies the changes).
